GET http://localhost:3000
###
POST http://localhost:3000/user/sign-up
Content-Type: application/json

{
    "username": "Guest",
    "password": "Password"
}
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "Guest",
    "password": "Password"
}
###
POST http://localhost:3000/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJHdWVzdCIsImlhdCI6MTczOTYwNTkzMH0.j4zPlOy0M23RuYiimRjmOMmB2XFTWGhIXvHHWKCZsMg
###
GET http://localhost:3000/user/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJHdWVzdCIsImlhdCI6MTczOTYwNTkzMH0.j4zPlOy0M23RuYiimRjmOMmB2XFTWGhIXvHHWKCZsMg
###
GET http://localhost:3000/posts/All
###
POST http://localhost:3000/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJHdWVzdCIsImlhdCI6MTczOTYwNTkzMH0.j4zPlOy0M23RuYiimRjmOMmB2XFTWGhIXvHHWKCZsMg

{
    "title": "some name",
    "content": "some content"
}
###
PUT http://localhost:3000/posts/update/67b1520af91003158a0ecde2
Content-Type: application/json

{
    "title":"some name",
    "content":"some content"
}
###
DELETE http://localhost:3000/posts/delete/67b16171edc75c598147c5b
###
GET http://localhost:3000/posts/all/something
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJHdWVzdCIsImlhdCI6MTczOTYwNTkzMH0.j4zPlOy0M23RuYiimRjmOMmB2XFTWGhIXvHHWKCZsMg
###
GET http://localhost:3000/posts/all